server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

cors.allow.origin: "*"

security:
  require-ssl: false
  ignored:
    - "/css/**"
    - "/js/**"
    - "/favicon.ico"
    - "/webjars/**"

spring:
  application:
    name: test-webapp

management:
  security:
    enabled: false

nfs.simulatorServlet.enabled: true

app:
  db:
    crypto:
      key: "MySuperSecretKey"
      webspherekeyset: ""

---
spring:
  profiles: test

security:
  require-ssl: false
  ignored:
    - "/**"

---
spring:
  profiles: oracle

  datasource:
    url: jdbc:oracle:thin:@//192.168.99.100:49161/XE
    username: spring
    password: spring

  jpa:
    database: oracle
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect

flyway:
  enabled: true
  locations: db/migration/oracle


---
spring:
  profiles: h2

  datasource:
    url: jdbc:h2:mem:tempdb;MODE=oracle;DB_CLOSE_ON_EXIT=FALSE
    username: sa

  jpa:
    database: H2
    show-sql: false
    hibernate:
      ddl-auto: create
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

flyway:
  enabled: false
  locations: db/migration/h2


