server:
  port: 8080

logging:
  level:
    root: INFO

cors.allow.origin: "*"

spring:
  application:
    name: rwb-leads-svc
  profiles:
    active: h2 
  datasource:
    url: jdbc:h2:mem:tempdb;MODE=oracle;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  #cache:
  #  type: hazelcast
  #hazelcast:
  #  config: my-hazelcast.xml      
    
security:
  basic:
    enabled: false

management:
  security:
    enabled: false    

flyway:
  enabled: false
  locations: db/migration/h2
  
katharsis:
  resource-package: com.sc.csl.retail.crm
  domain-name: http://localhost:8080
  path-prefix: /api  


