server:
  port: 8080

logging:
  level:
    root: INFO

cors.allow.origin: "*"

spring:
  application:
    name: rwb-leads-svc

management:
  security:
    enabled: false

---
spring:
  profiles: h2

  datasource:
    url: jdbc:h2:mem:tempdb;MODE=oracle;DB_CLOSE_ON_EXIT=FALSE
    username: sa

  jpa:
    database: H2
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

flyway:
  enabled: false
  locations: db/migration/h2


